# Generated by Django 6.0.2 on 2026-02-15 05:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vatsim_id', models.IntegerField(unique=True, verbose_name='VATSIM Event ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome do Evento')),
                ('link', models.URLField(blank=True, default='', max_length=500, verbose_name='Link')),
                ('banner_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Banner URL')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(verbose_name='Fim')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Descrição Curta')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição Completa')),
                ('organisers_json', models.JSONField(blank=True, null=True, verbose_name='Organizadores (JSON)')),
                ('airports_json', models.JSONField(blank=True, null=True, verbose_name='Aeroportos (JSON)')),
                ('routes_json', models.JSONField(blank=True, null=True, verbose_name='Rotas (JSON)')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberto para Bookings'), ('review', 'Em Revisão'), ('locked', 'Posições Travadas'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('block_duration_minutes', models.IntegerField(default=60, help_text='Tamanho de cada bloco de horário (ex: 30, 60, 120)', validators=[django.core.validators.MinValueValidator(15)], verbose_name='Duração do Bloco (minutos)')),
                ('discord_channel_id', models.CharField(blank=True, default='', max_length=20)),
                ('discord_message_id', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PositionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Posição')),
                ('min_rating', models.IntegerField(choices=[(1, 'OBS'), (2, 'S1'), (3, 'S2'), (4, 'S3'), (5, 'C1'), (6, 'C2'), (7, 'C3'), (8, 'I1'), (9, 'I2'), (10, 'I3'), (11, 'SUP'), (12, 'ADM')], default=2, help_text='Rating mínimo necessário para controlar esta posição', verbose_name='Rating Mínimo')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Template de Posição',
                'verbose_name_plural': 'Templates de Posição',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VATSIMUser',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, verbose_name='CID')),
                ('discord_user_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Discord User ID')),
                ('discord_username', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.IntegerField(choices=[(1, 'OBS'), (2, 'S1'), (3, 'S2'), (4, 'S3'), (5, 'C1'), (6, 'C2'), (7, 'C3'), (8, 'I1'), (9, 'I2'), (10, 'I3'), (11, 'SUP'), (12, 'ADM')], default=1, verbose_name='Rating ATC')),
                ('stats_json', models.JSONField(blank=True, help_text='Raw stats from the VATSIM API', null=True, verbose_name='Estatísticas VATSIM (JSON)')),
                ('total_applications', models.IntegerField(default=0, verbose_name='Total de Aplicações')),
                ('total_participations', models.IntegerField(default=0, verbose_name='Participações')),
                ('total_no_shows', models.IntegerField(default=0, verbose_name='No Shows')),
                ('total_cancellations', models.IntegerField(default=0, verbose_name='Cancelamentos')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Notas do Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membro VATSIM',
                'verbose_name_plural': 'Membros VATSIM',
                'ordering': ['-total_participations'],
            },
        ),
        migrations.CreateModel(
            name='EventICAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=4, verbose_name='Código ICAO')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icaos', to='core.event')),
            ],
            options={
                'verbose_name': 'ICAO do Evento',
                'verbose_name_plural': 'ICAOs do Evento',
                'ordering': ['icao'],
                'unique_together': {('event', 'icao')},
            },
        ),
        migrations.CreateModel(
            name='EventPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.eventicao', verbose_name='ICAO do Evento')),
                ('position_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.positiontemplate', verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Posição do Evento',
                'verbose_name_plural': 'Posições do Evento',
                'ordering': ['event_icao__icao', 'position_template__name'],
                'unique_together': {('event_icao', 'position_template')},
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(verbose_name='Número do Bloco')),
                ('start_time', models.DateTimeField(verbose_name='Início do Bloco')),
                ('end_time', models.DateTimeField(verbose_name='Fim do Bloco')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='core.event')),
            ],
            options={
                'verbose_name': 'Bloco de Horário',
                'verbose_name_plural': 'Blocos de Horário',
                'ordering': ['event', 'block_number'],
                'unique_together': {('event', 'block_number')},
            },
        ),
        migrations.CreateModel(
            name='BookingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('locked', 'Selecionado (Aguardando Confirmação)'), ('confirmed', 'Confirmado'), ('full_confirmed', 'Confirmação Final'), ('rejected', 'Não Selecionado'), ('cancelled', 'Cancelado pelo Usuário'), ('no_show', 'No Show')], default='pending', max_length=20, verbose_name='Status')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notificação Enviada')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Lembrete Enviado')),
                ('rejection_sent', models.BooleanField(default=False, verbose_name='Rejeição Enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.eventposition', verbose_name='Posição')),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.timeblock', verbose_name='Bloco de Horário')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.vatsimuser', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Aplicação de Booking',
                'verbose_name_plural': 'Aplicações de Booking',
                'ordering': ['time_block__block_number', 'event_position'],
                'unique_together': {('user', 'event_position', 'time_block')},
            },
        ),
    ]
