# Generated by Django 6.0.2 on 2026-02-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingapplication',
            name='dm_failure_count',
            field=models.IntegerField(default=0, verbose_name='Tentativas de DM Falhadas'),
        ),
        migrations.AddField(
            model_name='bookingapplication',
            name='dm_failure_notified',
            field=models.BooleanField(default=False, verbose_name='Admin Notificado sobre Falha de DM'),
        ),
    ]
