# Generated by Django 6.0.2 on 2026-02-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_dm_failure_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingapplication',
            name='fallback_channel_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID do Canal de Fallback'),
        ),
    ]
